FROM python:3.10

WORKDIR /app
COPY requeriments.txt /app/requeriments.txt

RUN pip install --no-cache-dir --upgrade -r /app/requeriments.txt

COPY . /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--post", "80"]